kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: ptarmiganlabs/butler-app-duplicator
    dockerfile: Dockerfile
    context: 
    # auto_tag: true
    tags:
    - latest
    - '3.0.3'
  when:
    event:
    - tag
